# SPDX-License-Identifier: Apache-2.0 OR MIT
# This file is @generated by formula.sh.
# It is not intended for manual editing.
class CargoLlvmCov < Formula
  desc "Cargo subcommand for LLVM source-based code coverage (-C instrument-coverage)"
  homepage "https://github.com/taiki-e/cargo-llvm-cov"
  version "0.5.34"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/cargo-llvm-cov/releases/download/v0.5.34/cargo-llvm-cov-aarch64-apple-darwin.tar.gz"
      sha256 "81eb3dc6dec49c1eb1a9eb5cbdd40395dbf62541be655c4df3ebb09276a5c0b1"
    else
      url "https://github.com/taiki-e/cargo-llvm-cov/releases/download/v0.5.34/cargo-llvm-cov-x86_64-apple-darwin.tar.gz"
      sha256 "f36ffdc068216d65618bced4213177a22f9fae8539070acdff4b84757940c98f"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/cargo-llvm-cov/releases/download/v0.5.34/cargo-llvm-cov-aarch64-unknown-linux-musl.tar.gz"
      sha256 "96ea303a801f640a205c3e53bd240ee22c51e02a4feb90ab879882ed9b774247"
    else
      url "https://github.com/taiki-e/cargo-llvm-cov/releases/download/v0.5.34/cargo-llvm-cov-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2d312925ea2178de060b5628c899f44f6a162ce621a87de8c3aa0658573f9641"
    end
  end

  def install
    bin.install "cargo-llvm-cov"
  end

  test do
    system "#{bin}/cargo-llvm-cov", "llvm-cov", "--version"
  end
end
