# This file is @generated by formula.sh.
# It is not intended for manual editing.
class CargoLlvmCov < Formula
  desc "Cargo subcommand for LLVM source-based code coverage (-C instrument-coverage)"
  homepage "https://github.com/taiki-e/cargo-llvm-cov"
  version "0.5.5"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/cargo-llvm-cov/releases/download/v0.5.5/cargo-llvm-cov-aarch64-apple-darwin.tar.gz"
      sha256 "00abbc5db882b766d92c08a7069902cbe3f183af066a42bf079f954fc32f3c29"
    else
      url "https://github.com/taiki-e/cargo-llvm-cov/releases/download/v0.5.5/cargo-llvm-cov-x86_64-apple-darwin.tar.gz"
      sha256 "870334436497fa4ec5aea8ca353688881ad9f8f6cc4ad61c4837de1f078d637b"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/cargo-llvm-cov/releases/download/v0.5.5/cargo-llvm-cov-aarch64-unknown-linux-musl.tar.gz"
      sha256 "a48b20d8f7ebf35949ba6e3419106afdfe638d1527ffeb5945385d51c82a443d"
    else
      url "https://github.com/taiki-e/cargo-llvm-cov/releases/download/v0.5.5/cargo-llvm-cov-x86_64-unknown-linux-musl.tar.gz"
      sha256 "58f459604beef46eff43d14fc41cb39437a2834bece9b91823cafce7a3e91428"
    end
  end

  def install
    bin.install "cargo-llvm-cov"
  end

  test do
    system "#{bin}/cargo-llvm-cov", "llvm-cov", "--version"
  end
end
