# SPDX-License-Identifier: Apache-2.0 OR MIT
# This file is @generated by formula.sh.
# It is not intended for manual editing.
class CargoMinimalVersions < Formula
  desc "Cargo subcommand for proper use of -Z minimal-versions"
  homepage "https://github.com/taiki-e/cargo-minimal-versions"
  # version "0.1.35"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/cargo-minimal-versions/releases/download/v0.1.35/cargo-minimal-versions-aarch64-apple-darwin.tar.gz"
      sha256 "600571a93e3e61feddf03ee7b614bc4c93fe79fc715803574d49507a3bc8933b"
    else
      url "https://github.com/taiki-e/cargo-minimal-versions/releases/download/v0.1.35/cargo-minimal-versions-x86_64-apple-darwin.tar.gz"
      sha256 "d6595bdace1c6337ec46195af8093b8a99713258030ff1cd074f51ddc59542fd"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/cargo-minimal-versions/releases/download/v0.1.35/cargo-minimal-versions-aarch64-unknown-linux-musl.tar.gz"
      sha256 "5440d849419497a5839bfe7a7f8bd46b6de23e6cd818712c87ae80a184fdc9f8"
    else
      url "https://github.com/taiki-e/cargo-minimal-versions/releases/download/v0.1.35/cargo-minimal-versions-x86_64-unknown-linux-musl.tar.gz"
      sha256 "7fc09551f7b4e4ae8903879706156150274348120d0c5a9683d77d0186ccf226"
    end
  end

  def install
    bin.install "cargo-minimal-versions"
  end

  test do
    system bin/"cargo-minimal-versions", "minimal-versions", "--version"
  end
end
