# This file is @generated by formula.sh.
# It is not intended for manual editing.
class CargoNoDevDeps < Formula
  desc "Cargo subcommand for running cargo without dev-dependencies"
  homepage "https://github.com/taiki-e/cargo-no-dev-deps"
  version "0.2.0"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/cargo-no-dev-deps/releases/download/v0.2.0/cargo-no-dev-deps-aarch64-apple-darwin.tar.gz"
      sha256 "9854154d4f044807dd1ad06c9b2a94f93e0f8551f44c90cab1a955eb909457a2"
    else
      url "https://github.com/taiki-e/cargo-no-dev-deps/releases/download/v0.2.0/cargo-no-dev-deps-x86_64-apple-darwin.tar.gz"
      sha256 "7eb91033a29c16c02a67162858adcd592804b3f393b981a3f0e00c1c3ce7a29c"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/cargo-no-dev-deps/releases/download/v0.2.0/cargo-no-dev-deps-aarch64-unknown-linux-musl.tar.gz"
      sha256 "085738eb7b1377034c2f569bd6a6402499a1f2e71d5e89bccaa5d85303c32627"
    else
      url "https://github.com/taiki-e/cargo-no-dev-deps/releases/download/v0.2.0/cargo-no-dev-deps-x86_64-unknown-linux-musl.tar.gz"
      sha256 "446d7879e260d1a6170ee105c211255e0729d2db50d4d6378c60ebc19b26b056"
    end
  end

  def install
    bin.install "cargo-no-dev-deps"
  end

  test do
    system "#{bin}/cargo-no-dev-deps", "no-dev-deps", "--version"
  end
end
