# This file is @generated by formula.sh.
# It is not intended for manual editing.
class CargoHack < Formula
  desc "Cargo subcommand for testing and continuous integration"
  homepage "https://github.com/taiki-e/cargo-hack"
  version "0.5.9"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/taiki-e/cargo-hack/releases/download/v0.5.9/cargo-hack-x86_64-apple-darwin.tar.gz"
      sha256 "38edacefb163c8f6b701c31a984fa6b1053747faf988354a7a0e2ef200618701"
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taiki-e/cargo-hack/releases/download/v0.5.9/cargo-hack-x86_64-unknown-linux-musl.tar.gz"
      sha256 "98f4010e94700ad342be575156b642be6669afc04ae62eec438d06bd1dd87b4d"
    end
  end

  def install
    bin.install "cargo-hack"
  end

  test do
    system "#{bin}/cargo-hack", "hack", "--version"
  end
end
