# This file is @generated by formula.sh.
# It is not intended for manual editing.
class CargoNoDevDeps < Formula
  desc "Cargo subcommand for running cargo without dev-dependencies"
  homepage "https://github.com/taiki-e/cargo-no-dev-deps"
  version "0.2.5"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/cargo-no-dev-deps/releases/download/v0.2.5/cargo-no-dev-deps-aarch64-apple-darwin.tar.gz"
      sha256 "125813b967068757faf1f9733ef018de0850a5e642e86d436b47b317202244ea"
    else
      url "https://github.com/taiki-e/cargo-no-dev-deps/releases/download/v0.2.5/cargo-no-dev-deps-x86_64-apple-darwin.tar.gz"
      sha256 "82aea3272e74f49f10afd04f8e7451831408b006dc97a6d36b56bb81bfe862ec"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/cargo-no-dev-deps/releases/download/v0.2.5/cargo-no-dev-deps-aarch64-unknown-linux-musl.tar.gz"
      sha256 "049696e69c9a1ed571dc93377e944c37e0c886517bc517a84de03a9591b0e013"
    else
      url "https://github.com/taiki-e/cargo-no-dev-deps/releases/download/v0.2.5/cargo-no-dev-deps-x86_64-unknown-linux-musl.tar.gz"
      sha256 "4c609f8d62669a8ecad8a83769e3a3adf5faab94820e69fd73473a37bfd39be4"
    end
  end

  def install
    bin.install "cargo-no-dev-deps"
  end

  test do
    system "#{bin}/cargo-no-dev-deps", "no-dev-deps", "--version"
  end
end
