# SPDX-License-Identifier: Apache-2.0 OR MIT
# This file is @generated by formula.sh.
# It is not intended for manual editing.
class ParseDockerfile < Formula
  desc "Dockerfile parser, written in Rust"
  homepage "https://github.com/taiki-e/parse-dockerfile"
  # version "0.1.1"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/parse-dockerfile/releases/download/v0.1.1/parse-dockerfile-aarch64-apple-darwin.tar.gz"
      sha256 "c91b6512ef18a51486065164cfd31d0acd5de1e47db94ef447b6d4f24e670ea6"
    else
      url "https://github.com/taiki-e/parse-dockerfile/releases/download/v0.1.1/parse-dockerfile-x86_64-apple-darwin.tar.gz"
      sha256 "d0f2192e66a9ac52f1624f0ff0543f701c6c8e5a690f63f21c481b5b3e3748eb"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/parse-dockerfile/releases/download/v0.1.1/parse-dockerfile-aarch64-unknown-linux-musl.tar.gz"
      sha256 "29c0a71340eb1bcc8033ae1f3e6e77afe921f8c5c3d6b2919c50c1d5eaab22b6"
    else
      url "https://github.com/taiki-e/parse-dockerfile/releases/download/v0.1.1/parse-dockerfile-x86_64-unknown-linux-musl.tar.gz"
      sha256 "b72138691c67e48d77b1c69c726bf9815edc9554144fc6eb513c2df02d31ffc9"
    end
  end

  def install
    bin.install "parse-dockerfile"
  end

  test do
    system bin/"parse-dockerfile", "--version"
  end
end
