# SPDX-License-Identifier: Apache-2.0 OR MIT
# This file is @generated by formula.sh.
# It is not intended for manual editing.
class ParseDockerfile < Formula
  desc "Dockerfile parser, written in Rust"
  homepage "https://github.com/taiki-e/parse-dockerfile"
  version "0.1.0"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/parse-dockerfile/releases/download/v0.1.0/parse-dockerfile-aarch64-apple-darwin.tar.gz"
      sha256 "c4eaff6be100426f2c36a08bc2aa0e3c323880b03fdf88e94c469eedcc9a276d"
    else
      url "https://github.com/taiki-e/parse-dockerfile/releases/download/v0.1.0/parse-dockerfile-x86_64-apple-darwin.tar.gz"
      sha256 "b50e59f1e232d64ae568bac1bf5ddd8f80bcd783b1d322373b5d603d63bce66c"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/parse-dockerfile/releases/download/v0.1.0/parse-dockerfile-aarch64-unknown-linux-musl.tar.gz"
      sha256 "68b4822d75300feab0a56d52a3a798ac447319a015e4c2e2de0d353979a109da"
    else
      url "https://github.com/taiki-e/parse-dockerfile/releases/download/v0.1.0/parse-dockerfile-x86_64-unknown-linux-musl.tar.gz"
      sha256 "9619a5811b9cc3cfa109135860469f4557de42cef776bc4b22b9459121ec6149"
    end
  end

  def install
    bin.install "parse-dockerfile"
  end

  test do
    system "#{bin}/parse-dockerfile", "--version"
  end
end
