# SPDX-License-Identifier: Apache-2.0 OR MIT
# This file is @generated by formula.sh.
# It is not intended for manual editing.
class ParseDockerfile < Formula
  desc "Dockerfile parser, written in Rust"
  homepage "https://github.com/taiki-e/parse-dockerfile"
  # version "0.1.3"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/parse-dockerfile/releases/download/v0.1.3/parse-dockerfile-aarch64-apple-darwin.tar.gz"
      sha256 "0c6a477da18bf5d5748b4f9797c7d648c5bd16155cb13b0466be2561f409c14e"
    else
      url "https://github.com/taiki-e/parse-dockerfile/releases/download/v0.1.3/parse-dockerfile-x86_64-apple-darwin.tar.gz"
      sha256 "a17cbcca768443eccbac2fb682760f66c04f6e807de069e46cd0df5c624cd079"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/taiki-e/parse-dockerfile/releases/download/v0.1.3/parse-dockerfile-aarch64-unknown-linux-musl.tar.gz"
      sha256 "aebe710820be9eaeb8cc553c223053689d1ef78252b2f376e0fb62d7d933ca09"
    else
      url "https://github.com/taiki-e/parse-dockerfile/releases/download/v0.1.3/parse-dockerfile-x86_64-unknown-linux-musl.tar.gz"
      sha256 "70c63736ac58d7d808d677d9bc5cc69a4e7e7cbb3a5a4d726d2bba7b1fb96452"
    end
  end

  def install
    bin.install "parse-dockerfile"
  end

  test do
    system bin/"parse-dockerfile", "--version"
  end
end
