name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: brew install --verbose Formula/*.rb
      - run: brew test --verbose Formula/*.rb
      - run: tools/audit.sh

  formula:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: tools/formula.sh
      - run: git diff --exit-code

  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Prettier
        run: npm install prettier
      - name: Install shfmt
        run: |
          "${GOROOT_1_17_X64}"/bin/go install mvdan.cc/sh/v3/cmd/shfmt@latest
          echo "${HOME}/go/bin" >>"${GITHUB_PATH}"
      - name: Install ShellCheck
        run: |
          sudo apt-get remove -y shellcheck
          tag="$(curl -fsSL --retry 3 https://api.github.com/repos/koalaman/shellcheck/releases/latest | jq -r '.tag_name')"
          curl -fsSL --retry 3 "https://github.com/koalaman/shellcheck/releases/download/${tag}/shellcheck-${tag}.linux.x86_64.tar.xz" \
            | tar xJf - --strip-components 1 -C /usr/local/bin "shellcheck-${tag}/shellcheck"
          shellcheck --version
      - run: tools/tidy.sh
