name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '40 1 * * *'

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: brew install --verbose Formula/*.rb
      - run: brew test --verbose Formula/*.rb
      - run: brew audit --strict Formula/*.rb

  formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tools/formula.sh
      - run: git diff --exit-code
