name: Formula

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  formula:
    uses: taiki-e/github-actions/.github/workflows/gen.yml@dc24bff2366e8ddeea5e0e4168df3d6f4b93f596 # 2026.8.8
    permissions:
      contents: write # for creating branch for pr
    secrets:
      PR_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PR_TOKEN_APP_PRIVATE_KEY }}
    with:
      script: tools/formula.sh
      commit-script: tools/ci/formula.sh
      title: Update formula
      branch: update-formula
